### ISSUE TITLE
Migrate to Rust

### ISSUE THREAD

**Issue by Akirtovskis** [bartaxyz/daily-tasks#1]

**Comment by bartaxyz** [comment]
Hello Akirtovskis 👋  Thank you for filling an issue here.

It's very critical for this project that it is built fast as I don't have a plethora of time to maintain it. Typescript, expo, and electron are very good for their iteration speeds. And, I'm already proficient in this tech.

But feel free to either fork this repo or even create a pull request! Maybe some rust solution would be viable to the restrictions I build around a project like this (mostly due to time pressure). I'd be happy to see it!

**Comment by bartaxyz** [comment]
@Akirtovskis Closing this PR due to inactivity. Feel free to share progress on rewriting this in Rust 🙌
